# Tên file thực thi
TARGET = bin/main.exe

# Trình biên dịch
CXX = g++

# Cấu hình đường dẫn
# -Iinclude giúp trình biên dịch tìm thấy các file .h trong thư mục include
CXXFLAGS = -std=c++17 -Iinclude

# Tìm tất cả file .cpp trong thư mục src/ VÀ file main.cpp ở gốc
SRCS = $(wildcard src/*.cpp) main.cpp

# Lệnh chạy mặc định
all: prep $(TARGET)

# Tạo thư mục bin nếu chưa có
prep:
	@if not exist bin mkdir bin

# Biên dịch trực tiếp ra file exe nằm trong bin/
$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET)

# Dọn dẹp bin
clean:
	@if exist bin rmdir /s /q bin